export default [
    {
      id: 1,
      titulo: "Ecos del Silencio",
      descripcion: 'Una obra maestra que captura la profundidad del silencio.',
      imagenes: 'https://cdn-7.nikon-cdn.com/Images/Learn-Explore/Photography-Techniques/2018/Mandy-Lea-landscapes/Media/Mandy-Lea-waterfall-8.low.jpg',
      url: './...',
      fecha: '2023-11-7',
    },
    {
      id: 2,
      titulo: "Amanecer en la Niebla",
      descripcion: 'La magia del amanecer entre la niebla en su máxima expresión.',
      imagenes: 'https://mott.pe/noticias/wp-content/uploads/2019/03/los-50-paisajes-maravillosos-del-mundo-para-tomar-fotos.jpg',
      url: './...',
      fecha: '2023-11-8',
    },
    {
      id: 3,
      titulo: "Melodía de Colores",
      descripcion: 'Una sinfonía visual que canta la belleza de los colores.',
      imagenes: 'https://cdn-7.nikon-cdn.com/Images/Learn-Explore/Photography-Techniques/2018/Mandy-Lea-landscapes/Media/Mandy-Lea-waterfall-8.low.jpg',
      url: './...',
      fecha: '2023-11-9',
    },
    {
      id: 4,
      titulo: "Reflejos en el Agua",
      descripcion: 'Un retrato etéreo de los reflejos en las aguas tranquilas.',
      imagenes: 'https://mott.pe/noticias/wp-content/uploads/2019/03/los-50-paisajes-maravillosos-del-mundo-para-tomar-fotos.jpg',
      url: './...',
      fecha: '2023-11-10',
    },
    {
      id: 5,
      titulo: "El Bosque Encantado",
      descripcion: 'Un viaje mágico al corazón de un bosque misterioso.',
      imagenes: 'https://cdn-7.nikon-cdn.com/Images/Learn-Explore/Photography-Techniques/2018/Mandy-Lea-landscapes/Media/Mandy-Lea-waterfall-8.low.jpg',
      url: './...',
      fecha: '2023-11-11',
    },
    {
      id: 6,
      titulo: "Paisaje Onírico",
      descripcion: 'Un paisaje que parece sacado de un sueño inolvidable.',
      imagenes: 'https://mott.pe/noticias/wp-content/uploads/2019/03/los-50-paisajes-maravillosos-del-mundo-para-tomar-fotos.jpg',
      url: './...',
      fecha: '2023-11-12',
    },
    {
      id: 7,
      titulo: "Luces de la Ciudad",
      descripcion: 'Las luces de la ciudad que nunca duermen en su esplendor.',
      imagenes: 'https://cdn-7.nikon-cdn.com/Images/Learn-Explore/Photography-Techniques/2018/Mandy-Lea-landscapes/Media/Mandy-Lea-waterfall-8.low.jpg',
      url: './...',
      fecha: '2023-11-13',
    },
    {
      id: 8,
      titulo: "Horizonte Dorado",
      descripcion: 'Un horizonte bañado en un oro líquido y cálido.',
      imagenes: 'https://mott.pe/noticias/wp-content/uploads/2019/03/los-50-paisajes-maravillosos-del-mundo-para-tomar-fotos.jpg',
      url: './...',
      fecha: '2023-11-14',
    },
    {
      id: 9,
      titulo: "Cielo Estrellado",
      descripcion: 'Un cielo lleno de estrellas como nunca lo has visto.',
      imagenes: 'https://cdn-7.nikon-cdn.com/Images/Learn-Explore/Photography-Techniques/2018/Mandy-Lea-landscapes/Media/Mandy-Lea-waterfall-8.low.jpg',
      url: './...',
      fecha: '2023-11-15',
    },
    {
      id: 10,
      titulo: "Retrato de la Naturaleza",
      descripcion: 'Un retrato íntimo de la belleza natural en su esplendor.',
      imagenes: 'https://mott.pe/noticias/wp-content/uploads/2019/03/los-50-paisajes-maravillosos-del-mundo-para-tomar-fotos.jpg',
      url: './...',
      fecha: '2023-11-16',
    },
    {
        id: 11,
        titulo: "Sueños en Acuarela",
        descripcion: 'Un mundo de sueños y emociones plasmado en acuarelas.',
        imagenes: 'URL de la imagen 11',
        url: './...',
        fecha: '2023-11-17',
      },
      {
        id: 12,
        titulo: "Puesta de Sol en Oro Líquido",
        descripcion: 'La majestuosidad de una puesta de sol dorada como el oro.',
        imagenes: 'URL de la imagen 12',
        url: './...',
        fecha: '2023-11-18',
      },
      {
        id: 13,
        titulo: "Reflejos de Cristal",
        descripcion: 'Un mundo de reflejos y cristales que despiertan la imaginación.',
        imagenes: 'URL de la imagen 13',
        url: './...',
        fecha: '2023-11-19',
      },
      {
        id: 14,
        titulo: "Universo en Miniatura",
        descripcion: 'Un cosmos completo en un pequeño rincón del mundo.',
        imagenes: 'URL de la imagen 14',
        url: './...',
        fecha: '2023-11-20',
      },
      {
        id: 15,
        titulo: "Arte en Movimiento",
        descripcion: 'La danza del arte en un viaje de movimiento y color.',
        imagenes: 'URL de la imagen 15',
        url: './...',
        fecha: '2023-11-21',
      },
      {
        id: 16,
        titulo: "Ecos del Pasado",
        descripcion: 'La nostalgia y la belleza de tiempos pasados capturados en arte.',
        imagenes: 'URL de la imagen 16',
        url: './...',
        fecha: '2023-11-22',
      },
      {
        id: 17,
        titulo: "Noche Estrellada",
        descripcion: 'Una noche estrellada que te hace soñar con el infinito.',
        imagenes: 'URL de la imagen 17',
        url: './...',
        fecha: '2023-11-23',
      },
      {
        id: 18,
        titulo: "Misterio en la Neblina",
        descripcion: 'Un mundo misterioso oculto entre la neblina y la oscuridad.',
        imagenes: 'URL de la imagen 18',
        url: './...',
        fecha: '2023-11-24',
      },
      {
        id: 19,
        titulo: "Aurora Luminosa",
        descripcion: 'El amanecer lleno de luces y colores que ilumina el horizonte.',
        imagenes: 'URL de la imagen 19',
        url: './...',
        fecha: '2023-11-25',
      },
      {
        id: 20,
        titulo: "Magia en la Ciudad",
        descripcion: 'La magia oculta en cada rincón de la vida urbana.',
        imagenes: 'URL de la imagen 20',
        url: './...',
        fecha: '2023-11-26',
      },
    // Agrega más proyectos con nombres y descripciones artísticas según sea necesario
  ];
  